### PR TITLE
Add summary about pull requests

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
Solves #16 

image

The data is fetched using the same web request and I just one slide more. So it should be fine regarding performance. I must admit though that I have no idea what I am doing here. So I wasn't running tests I just looked at it in the video editor.

I also thought about presenting the most liked pull request. I can detect it but I am not sure yet how to say nicely, that they don't have a pull request, that someone likes. So I ditched that idea for now although I still like my plan with the reaction emojis popping up.

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Thank you so much for the PR! What do you think about showing PRs instead of commits if one has contributed a lot? That way the duration would stay the same.

**Comment by JoshuaBehrens** [comment]
I mean they are similar in structure. Unfortunately PRs can't be queried exactly like the pull request. But I like your idea. How about replacing one or two random commits with pull requests from one of the predefined user analysis fields like the most reacted pull request. This way there is safe a memorable one in there. Not just random stuff

**Comment by JonnyBurger** [comment]
Ok, I would be down for a hybrid commits / PR panel as well!
I reset the extra scene for now to reflect this. Important: There also needs to be a fallback for those who have the old stats cached in the database.

Are you down to implement it like this?

**Comment by JoshuaBehrens** [comment]
> There also needs to be a fallback for those who have the old stats cached in the database.

I am new to remotion and React. Therefore I was only looking into, what copy-paste and rename leads to my goal. I wasn't noticing a caching layer but I assume you have it somewhere between getting the data from GitHub and transforming them into the scene data structures. I guess if I just make everything I have nullable/undefinable then we are good, aren't we?

Anything bad about clearing caches? Is it about that with these changes the videos would change for them as well?

> Are you down to implement it like this?

Yeah! 🤘

**Comment by JonnyBurger** [comment]
> I am new to remotion and React. Therefore I was only looking into, what copy-paste and rename leads to my goal. I wasn't noticing a caching layer but I assume you have it somewhere between getting the data from GitHub and transforming them into the scene data structures. I guess if I just make everything I have nullable/undefinable then we are good, aren't we?

Yes, the pull request field can just be nullable (marked as being able to be `undefined`) since the items in the database don't have it. Then TypeScript will kind of force you to handle it and everything will be fine!

> Anything bad about clearing caches? Is it about that with these changes the videos would change for them as well?

We right now have about 60.000 renders in the database and it cost about $2500 in server costs to generate the videos, so we'd like to avoid deleting all of the videos.

Sorry I won't help pushing this across the finishing line as much as I normally do, since I worked pretty hard on it the past three weeks I'm now a bit tired of it! :')

**Comment by JoshuaBehrens** [comment]
image
image

I cleaned up my early changes, I merged the most recent and most discussed pull request in there.

> We right now have about 60.000 renders in the database and it cost about $2500 in server costs to generate the videos, so we'd like to avoid deleting all of the videos.

That is quite a lot. Understood :) As a person of doing lots of pull request it would be cool to have a render of my unwrapped with the pull request statistics. Can you show me how to render it locally? Then I can pay my own bucks for it :)

Yeah, I've done some Typescript in the past. I am not very used to the jsx/tsx but it worked out quite well.

> Sorry I won't help pushing this across the finishing line [...] I'm now a bit tired of it! :')

Dude, you did quite an impressive project here. Having 60k rendered videos also just shows how much this is picked up by the community. This is a lot. That is also the reason why I do pull requests like this. To support such projects I can often contribute best by adding features or ironing out some kinks. I have some of these projects myself and I bet you have a pile of shame of projects you carry yourself as well. This is a finished one and it is damn good! You see the issues and pull requests coming in. Now we push it further. You just have to nod and merge :) OR obviously!!! decline if stuff does not match the project. Like having longer videos.

**Comment by JonnyBurger** [comment]
Super nice! 🙌🏼 looks good on first sight!

I plan on merging and deploying it, right now I don't have a computer though for the next few days, I will do that once I get back.

Thanks for the nice PR and message, and happy holidays!

**Comment by JoshuaBehrens** [comment]
> right now I don't have a computer though for the next few days

Right choice!

Will be happy to see that one merged :) Have some relaxing holidays as well!

**Comment by JonnyBurger** [comment]
Deploying! Thanks so much for your contribution! 🙌 

Although the amount of people that are getting their Unwrapped is slowing down (still expect a few thousand people to get the PR feature) this is also super helpful for next year where hopefully tens of thousands of people will get it :)

> Dude, you did quite an impressive project here. Having 60k rendered videos also just shows how much this is picked up by the community. This is a lot. 

Thanks a lot for the appreciation! 💙

**Comment by JoshuaBehrens** [comment]
Thank you for merging it :) got my self a reminder for next year :)

**Pull request merged**
